# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stable_pdf <- function(x, pars, parametrization = 0L, tol = 1e-12) {
    .Call('libstableR_stable_pdf', PACKAGE = 'libstableR', x, pars, parametrization, tol)
}

stable_cdf <- function(x, pars, parametrization = 0L, tol = 1e-12) {
    .Call('libstableR_stable_cdf', PACKAGE = 'libstableR', x, pars, parametrization, tol)
}

stable_q <- function(p, pars, parametrization = 0L, tol = 1e-12) {
    .Call('libstableR_stable_q', PACKAGE = 'libstableR', p, pars, parametrization, tol)
}

stable_rnd <- function(N, pars, parametrization = 0L, seed = 0L) {
    .Call('libstableR_stable_rnd', PACKAGE = 'libstableR', N, pars, parametrization, seed)
}

stable_fit_init <- function(rnd, parametrization = 0L) {
    .Call('libstableR_stable_fit_init', PACKAGE = 'libstableR', rnd, parametrization)
}

stable_fit_koutrouvelis <- function(rnd, pars_init = as.numeric( c()), parametrization = 0L) {
    .Call('libstableR_stable_fit_koutrouvelis', PACKAGE = 'libstableR', rnd, pars_init, parametrization)
}

stable_fit_mle <- function(rnd, pars_init = as.numeric( c()), parametrization = 0L) {
    .Call('libstableR_stable_fit_mle', PACKAGE = 'libstableR', rnd, pars_init, parametrization)
}

stable_fit_mle2d <- function(rnd, pars_init = as.numeric( c()), parametrization = 0L) {
    .Call('libstableR_stable_fit_mle2d', PACKAGE = 'libstableR', rnd, pars_init, parametrization)
}

