# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
stable_pdf <- function(x, pars, parametrization = 0L, tol = 1e-12) {
    .Call(`_libstableR_stable_pdf`, x, pars, parametrization, tol)
}

#' @export
stable_cdf <- function(x, pars, parametrization = 0L, tol = 1e-12) {
    .Call(`_libstableR_stable_cdf`, x, pars, parametrization, tol)
}

#' @export
stable_q <- function(p, pars, parametrization = 0L, tol = 1e-12) {
    .Call(`_libstableR_stable_q`, p, pars, parametrization, tol)
}

#' @export
stable_rnd <- function(N, pars, parametrization = 0L, seed = 0L) {
    .Call(`_libstableR_stable_rnd`, N, pars, parametrization, seed)
}

#' @export
stable_fit_init <- function(rnd, parametrization = 0L) {
    .Call(`_libstableR_stable_fit_init`, rnd, parametrization)
}

#' @export
stable_fit_koutrouvelis <- function(rnd, pars_init = as.numeric( c()), parametrization = 0L) {
    .Call(`_libstableR_stable_fit_koutrouvelis`, rnd, pars_init, parametrization)
}

#' @export
stable_fit_mle <- function(rnd, pars_init = as.numeric( c()), parametrization = 0L) {
    .Call(`_libstableR_stable_fit_mle`, rnd, pars_init, parametrization)
}

#' @export
stable_fit_mle2d <- function(rnd, pars_init = as.numeric( c()), parametrization = 0L) {
    .Call(`_libstableR_stable_fit_mle2d`, rnd, pars_init, parametrization)
}

